# https://acouvreur.github.io/sablier/#/plugins/traefik
# https://acouvreur.github.io/sablier/#/strategies
http:
  middlewares:
    sablier-dynamic:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          names: whoami,nginx,mariadb
          dynamic:
            displayName: whoami
            refreshFrequency: 1s
            showDetails: true
            theme: shuffle

    sablier-blocking:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          names: whoami
          blocking:
            defaultTimeout: 10s
